(ns org.lotuc.durabletask.protocol)

(defprotocol DurableTaskClient
  (hello [_])
  (startInstance [_ req])
  (getInstance [_ req])
  (rewindInstance [_ req])
  (waitForInstanceStart [_ req])
  (waitForInstanceCompletion [_ req])
  (raiseEvent [_ req])
  (terminateInstance [_ req])
  (suspendInstance [_ req])
  (resumeInstance [_ req])
  (queryInstances [_ req])
  (purgeInstances [_ req])
  (getWorkItems [_ req])
  (completeActivityTask [_ req])
  (completeOrchestratorTask [_ req])
  (completeEntityTask [_ req])
  (createTaskHub [_ req])
  (deleteTaskHub [_ req])
  (signalEntity [_ req])
  (getEntity [_ req])
  (queryEntities [_ req])
  (cleanEntityStorage [_ req]))
